import:
  - ~/.alacritty-colorscheme/themes/monokai_pro.yaml

env:
  TERM: xterm-256color


font:
  normal:
    family: 'Hack Nerd Font Mono'
    style: Regular
  bold:
    family: 'Hack Nerd Font Mono'
    style: Regular
  italic:
    family: 'Hack Nerd Font Mono'
    style: Italic
  bold_italic:
    family: 'Hack Nerd Font Mono'
    style: Italic

  size: 14.0

  offset:
    x: 0
    y: 2
  glyph_offset:
    x: 0
    y: 2

window:
  padding:
    x: 12
    y: 12

scrolling:
  history: 3000
  multiplier: 4

cursor:
  style:
    shape: Block

draw_bold_text_with_bright_colors: false

selection:
  semantic_escape_chars: ',│`|:"'' ()[]{}<>'
  save_to_clipboard: true

live_config_reload: true

key_bindings:
  #- { key: R, mods: Command, mode: ~Vi|~Search, chars: "\x0c" }
  #- { key: R, mods: Command, mode: ~Vi|~Search, action: ClearHistory }
  - { key: W, mods: Command|Shift, chars: "\x1c&" }
  - { key: N,        mods: Command, command: { program: "open", args: ["-n", "/Applications/Alacritty.app"] } }
    #- { key: N, mods: Command, action: CreateNewWindow }
  - { key: Left, mods: Alt, chars: "\x1bb" } # Skip word left
  - { key: Right, mods: Alt, chars: "\x1bf" } # Skip word right
  - { key: Left, mods: Command, chars: "\x01" } # Home
  - { key: Right, mods: Command, chars: "\x05" } # End
  - { key: Back, mods: Command, chars: "\x15" } # Delete line
  - { key: Back, mods: Alt, chars: "\x1b\x7f" } # Delete word
  - { key: T, mods: Command, chars: "\x1cc" } # new tab with default shell
    #- { key: W, mods: Control, chars: "\x1c&" } # close the tab
  - { key: LBracket, mods: Command|Shift, chars: "\x1cp" } # go to previous tab
  - { key: RBracket, mods: Command|Shift, chars: "\x1cn" } # go to next tab
  - { key: Key1, mods: Command, chars: "\x1c1" } # go to tab 1..9
  - { key: Key2, mods: Command, chars: "\x1c2" }
  - { key: Key3, mods: Command, chars: "\x1c3" }
  - { key: Key4, mods: Command, chars: "\x1c4" }
  - { key: Key5, mods: Command, chars: "\x1c5" }
  - { key: Key6, mods: Command, chars: "\x1c6" }
  - { key: Key7, mods: Command, chars: "\x1c7" }
  - { key: Key8, mods: Command, chars: "\x1c8" }
  - { key: Key9, mods: Command, chars: "\x1c9" }
  - { key: Back, action: ReceiveChar }
